baseURL = "https://www.harryday.net/"
languageCode = "en-gb"
title = "Harry Day"
theme = "one"
publishDir = "docs"
googleAnalytics = "UA-119127686-1"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
    navigation = ["about.md","contact.md"]